Repository ESGForumWebSiteDev/project_ESGForumWebSiteDev_react-deployment-repo, pull requests merged in 2023-08, with the labels that each got.

#13 feat: make AboutUs and Seminars features
  .env.example
  .gitignore
  package.json
  src/Router.tsx
  src/assets/icons/aboutus-network.svg
  src/assets/icons/aboutus-research.svg
  src/assets/icons/aboutus-support.svg
  src/assets/icons/aboutus-value.svg
  src/assets/icons/subhome.svg
  src/components/aboutus/DesContent.tsx
  src/components/aboutus/HisConent.tsx
  src/components/aboutus/Layout.tsx
  src/components/aboutus/PageTitle.tsx
  src/components/aboutus/UFESGI.tsx
  src/components/layout/header/index.tsx
  src/components/layout/subnav/index.tsx
  src/custom.d.ts
  src/pages/aboutus/boe.tsx
  src/pages/aboutus/contact.tsx
  src/pages/aboutus/history.tsx
  src/pages/aboutus/index.tsx
  src/pages/aboutus/meetings.tsx
  src/pages/aboutus/objective.tsx
  src/pages/aboutus/rules.tsx
  src/pages/seminars.tsx
  src/services/aboutus.service.ts
  src/services/seminar.service.ts
  src/types/aboutus.interface.ts
  src/types/seminars.interface.ts
  tsconfig.json
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#14 feat(component): Implement CommitteeInfo page
  src/Router.tsx
  src/components/layout/dashboard/spinner.tsx
  src/components/layout/dashboard/statisticsCard.tsx
  src/components/widget/cards/addMemberModal.tsx
  src/components/widget/cards/tableBodyApplicants.tsx
  src/components/widget/cards/tableBodyCommittee.tsx
  src/components/widget/cards/tableBodyMembers.tsx
  src/components/widget/cards/tableBodySubscribers.tsx
  src/data/committeeMemberData.ts
  src/data/index.ts
  src/data/memberData.ts
  src/data/statisticsCardsData.ts
  src/data/subscriberData.ts
  src/data/userData.ts
  src/pages/admin/committee.tsx
  src/pages/admin/dashboard.tsx
Labels: 🔨 Refactor, ✨ Feature, 📬 API, 🎨 Html&css, 🐞 BugFix

#15 feat: Add configuration of quill editor functionally
  package.json
  src/assets/icons/seminars-search.svg
  src/components/editor/configure.js
  src/components/editor/quill-editor.tsx
  src/pages/aboutus/objective.tsx
  src/pages/seminars.tsx
  src/services/upload.service.ts
  yarn.lock
Labels: 🔨 Refactor, ✨ Feature, 📬 API

#17 refactor(token): Refactor token handling with hooks
  src/hooks/useToken.ts
  src/hooks/useValidateToken.ts
Labels: 🔨 Refactor

#18 feat: Add Members page component implementation
  .env.example
  package.json
  src/Router.tsx
  src/components/layout/dashboard/statisticsCard.tsx
  src/components/layout/login/index.tsx
  src/components/layout/table/tableHead.tsx
  src/components/widget/cards/addMemberModal.tsx
  src/components/widget/cards/statisticsCard.tsx
  src/components/widget/cards/tableBodyApplicants.tsx
  src/components/widget/cards/tableBodyMembers.tsx
  src/data/committeeData.ts
  src/data/committeeMemberData.ts
  src/data/memberData.ts
  src/data/userData.ts
  src/pages/admin/committee.tsx
  src/pages/admin/dashboard.tsx
  src/pages/admin/members.tsx
Labels: ✨ Feature, 📬 API, 🎨 Html&css, 🐞 BugFix

#20 ci: Add Docker configuration for CI/CD
  .dockerignore
  Dockerfile
  nginx.conf
  package.json
  src/pages/aboutus/history.tsx
  yarn.lock
Labels: 🔨 Refactor, 🌏 Deploy

#23 feat(quill-editor): add file attachment logic to the quill-editor component
  .gitignore
  src/assets/icons/editor-attachment.svg
  src/components/editor/Attachments.tsx
  src/components/editor/quill-editor.tsx
  yarn.lock
Labels: ✨ Feature
