Repository ESGForumWebSiteDev/project_ESGForumWebSiteDev_react-deployment-repo, pull requests merged in 2023-09, with the labels that each got.

#33 CI: add arg for deployment without .env
  Dockerfile
  src/pages/aboutus/rules.tsx
Labels: ⚙ Setting, 🌏 Deploy

#34 ci: GitHub Actions for CI testing2
  Dockerfile
  src/Router.tsx
  src/components/aboutus/Layout.tsx
  src/components/aboutus/SignatureCard.tsx
  src/components/editor/Attachments.tsx
  src/components/layout/dashboard/committeeTable.tsx
  src/components/layout/dashboard/statisticsCard.tsx
  src/components/layout/subnav/index.tsx
  src/components/widget/cards/addCommitteeModal.tsx
  src/components/widget/cards/statisticsCard.tsx
  src/components/widget/cards/tableBodyApplicants.tsx
  src/components/widget/cards/tableBodyCommittee.tsx
  src/components/widget/cards/tableBodyMembers.tsx
  src/data/committeeData.ts
  src/data/committeeMemberData.ts
  src/data/index.ts
  src/data/memberData.ts
  src/data/statisticsCardsData.ts
  src/data/userData.ts
  src/pages/aboutus/greetings.tsx
  src/pages/aboutus/meetings.tsx
  src/pages/aboutus/rules.tsx
  src/pages/admin/committee.tsx
  src/pages/admin/dashboard.tsx
  src/pages/admin/members.tsx
  src/pages/admin/users.tsx
  src/services/aboutus.service.ts
  src/services/request.service.ts
  src/types/aboutus.interface.ts
  src/types/admin.interface.ts
Labels: 🌏 Deploy

#35 refactor: remove unnecessary imports and clean up, fix incorrect import in router
  src/Router.tsx
  src/pages/aboutus/greetings.tsx
  src/pages/login.tsx
  src/pages/notification.tsx
  src/pages/notification_detail.tsx
  src/pages/reference.tsx
  src/pages/seminars.tsx
Labels: 🔨 Refactor, 🐞 BugFix

#36 refactor: remove unnecessary imports and clean up, fix incorrect import in router
  src/Router.tsx
  src/pages/aboutus/greetings.tsx
  src/pages/login.tsx
  src/pages/notification.tsx
  src/pages/notification_detail.tsx
  src/pages/reference.tsx
  src/pages/seminars.tsx
Labels: 🔨 Refactor, 🐞 BugFix

#32 feat(committee): add member email
  src/components/layout/header/index.tsx
  src/components/layout/table/index.tsx
  src/pages/committee.tsx
Labels: 🔨 Refactor, ✨ Feature, 🎨 Html&css

#39 cicd(build): add cache directory to yarn install command
  Dockerfile
Labels: 🌏 Deploy

#37 refactor(board): modify table header width
  src/pages/seminars.tsx
Labels: 🔨 Refactor, 🎨 Html&css

#38 feat: Implement Members component to display forum member information
  src/Router.tsx
  src/components/layout/dashboard/applicants.tsx
  src/components/layout/dashboard/committeeTable.tsx
  src/components/layout/dashboard/members.tsx
  src/components/layout/dashboard/spinner.tsx
  src/components/layout/dashboard/statisticsCard.tsx
  src/components/layout/dashboard/users.tsx
  src/components/widget/cards/statisticsCard.tsx
  src/components/widget/cards/tableBodyApplicants.tsx
  src/pages/admin/committee.tsx
  src/pages/admin/dashboard.tsx
  src/types/admin.interface.ts
Labels: 🔨 Refactor, 📬 API, 🎨 Html&css

#30 refactor(css) : edit folder paths and file names
  package.json
  src/Router.tsx
  src/assets/main/main-bg.png
  src/assets/main/p-1.jpg
  src/assets/main/p-2.jpg
  src/assets/main/p-3.jpg
  src/assets/main/p-4.jpg
  src/components/layout/footer/Footer.tsx
  src/components/main/Esg.tsx
  src/components/main/Navbar.tsx
  src/components/main/Singlepage.tsx
  src/components/main/Ufesgi.tsx
  src/custom.d.ts
  src/declarations.d.ts
  src/pages/index.tsx
  src/pages/main/App.css
  src/pages/main/index.css
  src/pages/main/index.tsx
  tailwind.config.js
  yarn.lock
Labels: 🔨 Refactor, ✨ Feature, 🎨 Html&css

#43 feat(members): add member management feature
  src/components/layout/dashboard/applicants.tsx
  src/components/layout/dashboard/committeeTable.tsx
  src/components/layout/dashboard/members.tsx
  src/components/layout/dashboard/statisticsCard.tsx
  src/components/widget/cards/addCommitteeMemberModal.tsx
  src/components/widget/cards/statisticsCard.tsx
  src/components/widget/cards/tableBodyMembers.tsx
  src/pages/admin/committee.tsx
  src/pages/admin/dashboard.tsx
  src/types/admin.interface.ts
Labels: 🔨 Refactor, ✨ Feature, 📬 API, 🐞 BugFix

#44 style(AboutUs): modify the font on the AboutUs page
  src/assets/css/web-font.css
  src/components/aboutus/DesContent.tsx
  src/components/aboutus/HisConent.tsx
  src/index.css
  yarn.lock
Labels: 🎨 Html&css

#45 feat(admin): implement delete button logic ...
  src/App.tsx
  src/components/layout/header/index.tsx
  src/hooks/useToken.ts
  src/pages/notification_detail.tsx
  src/pages/reference_detail.tsx
  src/pages/seminar_detail.tsx
  src/pages/seminars.tsx
  src/services/login.service.ts
  src/services/seminar.service.ts
Labels: 🔨 Refactor, ✨ Feature, 📬 API, 🎨 Html&css

#46 feat(seminars): add seminar_detail
  package.json
  src/Router.tsx
  src/assets/icons/write.svg
  src/components/editor/Attachments.tsx
  src/components/editor/ReadContents.tsx
  src/components/editor/editor-configure.js
  src/components/editor/quill-editor.tsx
  src/components/editor/read-configure.js
  src/pages/seminar_detail.tsx
  src/pages/seminar_post.tsx
  src/pages/seminars.tsx
  tailwind.config.js
  yarn.lock
Labels: 🔨 Refactor, ✨ Feature, 🎨 Html&css

#49 feat: Registering logos and resolving MOMENT errors for add yarn
  .gitignore
  package.json
  src/components/aboutus/bg_history.png
  src/components/layout/footer/Footer.tsx
  src/components/layout/header/esg-logo.svg
  src/components/layout/header/index.tsx
  src/declarations.d.ts
  src/pages/index.tsx
  src/pages/seminar_post.tsx
  yarn.lock
Labels: ⚙ Setting, 🎨 Html&css

#51 feat : Modify table column and Implement member management logic
  src/components/layout/dashboard/applicants.tsx
  src/components/layout/dashboard/committeeTable.tsx
  src/components/layout/dashboard/members.tsx
  src/components/layout/dashboard/users.tsx
  src/components/layout/login/index.tsx
  src/components/widget/cards/addMemberModal.tsx
  src/components/widget/cards/tableBodyCommittee.tsx
  src/components/widget/cards/tableBodyMembers.tsx
  src/pages/admin/committee.tsx
  src/pages/admin/dashboard.tsx
  src/pages/login.tsx
  src/services/member.service.ts
  src/types/admin.interface.ts
Labels: 🔨 Refactor, ✨ Feature, 🎨 Html&css, 🐞 BugFix

#52 feat(seminar): implement seminar edit page
  src/Router.tsx
  src/assets/icons/esg-logo.svg
  src/components/layout/header/index.tsx
  src/pages/notification_detail.tsx
  src/pages/reference_detail.tsx
  src/pages/seminar_detail.tsx
  src/pages/seminar_edit.tsx
  src/services/seminar.service.ts
Labels: 🔨 Refactor, ✨ Feature, 🎨 Html&css

#53 feat(board): implement board edit function
  src/Router.tsx
  src/pages/notification_detail.tsx
  src/pages/notification_edit.tsx
  src/pages/reference_detail.tsx
  src/pages/reference_edit.tsx
  src/services/post.service.ts
  src/services/user.service.ts
Labels: ✨ Feature, 📬 API, 🎨 Html&css

#54 feat(post posts): add temporary save logic
  package.json
  src/Router.tsx
  src/pages/notification.tsx
  src/pages/notification_detail.tsx
  src/pages/notification_edit.tsx
  src/pages/notification_post.tsx
  src/pages/reference.tsx
  src/pages/reference_edit.tsx
  src/pages/reference_post.tsx
  src/pages/seminar_edit.tsx
  src/pages/seminar_post.tsx
  src/types/post.interface.ts
  src/types/react-datetime-picker.type.ts
  tailwind.config.js
  yarn.lock
Labels: 🔨 Refactor, ✨ Feature, 🎨 Html&css

#55 refactor(board): add admin authority
  src/pages/index.tsx
  src/pages/notification.tsx
  src/pages/notification_detail.tsx
  src/pages/reference.tsx
  src/pages/reference_detail.tsx
  src/pages/seminar_detail.tsx
  src/pages/seminars.tsx
  src/types/seminars.interface.ts
Labels: 🔨 Refactor

#57 feat(header): add admin page button
  src/Router.tsx
  src/assets/icons/business-cowork.svg
  src/assets/icons/business-education.svg
  src/assets/icons/business-management.svg
  src/assets/icons/business-practice.svg
  src/assets/icons/business-research.svg
  src/assets/icons/business-support.svg
  src/components/layout/header/index.tsx
  src/components/layout/index.tsx
  src/components/main/Esg.tsx
  src/components/main/Navbar.tsx
  src/components/main/Singlepage.tsx
  src/components/main/Ufesgi.tsx
  src/hooks/useValidateToken.ts
  src/pages/business.tsx
  src/pages/committee.tsx
  src/pages/login.tsx
  src/pages/main/index.tsx
  src/pages/notification.tsx
  src/pages/notification_detail.tsx
  src/pages/notification_edit.tsx
  src/pages/notification_post.tsx
  src/pages/reference.tsx
  src/pages/reference_detail.tsx
  src/pages/reference_edit.tsx
  src/pages/reference_post.tsx
  src/pages/register.tsx
  src/pages/seminar_detail.tsx
  src/pages/seminar_edit.tsx
  src/pages/seminar_post.tsx
  src/pages/seminars.tsx
  src/services/post.service.ts
  src/services/seminar.service.ts
  src/services/upload.service.ts
  src/services/user.service.ts
Labels: 🔨 Refactor, ✨ Feature, 📬 API, 🎨 Html&css

#58 refactor(Router): modify route settings
  src/Router.tsx
  src/components/layout/header/index.tsx
  src/components/layout/subnav/index.tsx
  src/pages/aboutus/index.tsx
Labels: 🔨 Refactor

#61 refactor custum axios instance to function and refactor custum color and implement custom color
  src/components/layout/dashboard/applicants.tsx
  src/components/layout/dashboard/committeeMembers.tsx
  src/components/layout/dashboard/committeeTable.tsx
  src/components/layout/dashboard/members.tsx
  src/pages/admin/committee.tsx
  src/pages/admin/dashboard.tsx
  src/pages/login.tsx
  src/services/request.service.ts
  tailwind.config.js
Labels: 🔨 Refactor, 🐞 BugFix

#62 refactor: modify background image
  .gitignore
  src/assets/img/history-bg.png
  src/components/aboutus/PageTitle.tsx
  src/components/layout/card/index.tsx
  src/components/layout/subnav/index.tsx
  src/pages/aboutus/objective.tsx
Labels: 🔨 Refactor, 🎨 Html&css

#63 ci: GitHub Actions for CI testing5
  .gitignore
  src/assets/img/history-bg.png
  src/components/aboutus/PageTitle.tsx
  src/components/layout/card/index.tsx
  src/components/layout/dashboard/applicants.tsx
  src/components/layout/dashboard/committeeMembers.tsx
  src/components/layout/dashboard/committeeTable.tsx
  src/components/layout/dashboard/members.tsx
  src/components/layout/subnav/index.tsx
  src/pages/aboutus/objective.tsx
  src/pages/admin/committee.tsx
  src/pages/admin/dashboard.tsx
  src/pages/login.tsx
  src/services/request.service.ts
  tailwind.config.js
Labels: 🌏 Deploy

#64 refactor(business): modify route url
  src/pages/business.tsx
  src/pages/login.tsx
Labels: 🔨 Refactor, 📬 API

#66 fix styling
  src/components/layout/dashboard/applicants.tsx
  src/components/layout/dashboard/committeeMembers.tsx
  src/components/layout/dashboard/members.tsx
  src/pages/admin/committee.tsx
Labels: 🎨 Html&css

#67 style: Modify code formatting for consistency
  src/components/aboutus/DesContent.tsx
  src/components/aboutus/PageTitle.tsx
  src/components/layout/subnav/index.tsx
  src/pages/aboutus/history.tsx
  src/pages/aboutus/rules.tsx
  src/pages/notification_detail.tsx
  src/pages/reference_detail.tsx
  src/pages/seminar_detail.tsx
  src/pages/seminar_post.tsx
  tailwind.config.js
Labels: 🔨 Refactor, 🎨 Html&css

#68 Modify the NAV partial CSS
  src/components/aboutus/Layout.tsx
  src/components/aboutus/PageTitle.tsx
  src/components/layout/header/index.tsx
  src/components/layout/subnav/index.tsx
Labels: 🎨 Html&css

#70 style(aboutus): Set PageTitle background color for aboutus page
  public/favicon.ico
  public/favicon_.ico
  public/index.html
  src/pages/aboutus/boe.tsx
  src/pages/aboutus/contact.tsx
  src/pages/aboutus/greetings.tsx
  src/pages/aboutus/history.tsx
  src/pages/aboutus/rules.tsx
Labels: 🎨 Html&css

#71 style(Footer): modify footer area and fix awkward style
  public/favicon.ico
  public/favicon_.ico
  public/index.html
  src/Router.tsx
  src/components/layout/index.tsx
  src/pages/aboutus/boe.tsx
  src/pages/aboutus/contact.tsx
  src/pages/aboutus/greetings.tsx
  src/pages/aboutus/history.tsx
  src/pages/aboutus/rules.tsx
  src/pages/committee.tsx
Labels: 🔨 Refactor, 🎨 Html&css

#73 style: comment out unused file attachment tags
  src/Router.tsx
  src/components/layout/index.tsx
  src/pages/aboutus/contact.tsx
  src/pages/committee.tsx
  src/pages/notification_detail.tsx
  src/pages/reference_detail.tsx
  src/pages/seminar_detail.tsx
Labels: 🎨 Html&css

#74 ci: GitHub Actions for CI testing
  src/pages/notification_detail.tsx
  src/pages/reference_detail.tsx
  src/pages/seminar_detail.tsx
Labels: 🌏 Deploy
